/**
 * FaucetManager contract address on regtest.
 * Auto-generated by deploy script — do not edit manually.
 */
export const FAUCET_MANAGER_ADDRESS =
    'opr1sqqghwes985n4knlpfdar5n69luxj4afa7c4lvm70';
