/**
 * FaucetManager contract address on regtest.
 * Auto-generated by deploy script — do not edit manually.
 */
export const FAUCET_MANAGER_ADDRESS =
    'opr1sqp6y35l3tndp99nwued0stp7t53h8wm50yge002r';
