/**
 * FaucetManager contract address on regtest.
 * Auto-generated by deploy script — do not edit manually.
 */
export const FAUCET_MANAGER_ADDRESS =
    'opr1sqq5qe4e0d9u5h5m3ua54n02r2jjsm5n56y4asjx5';
